### ISSUE TITLE
fails to build with cmake 3.5rc

### ISSUE THREAD

**Issue by a-detiste** [dscharrer/innoextract#50]
```
/builddir/build/BUILD/innoextract-1.5/release.cpp
/builddir/build/BUILD/innoextract-1.5/release.cpp:31:6: error: operator '!=' has no left operand
 #if  != 5
      ^~
/builddir/build/BUILD/innoextract-1.5/release.cpp:35:6: error: operator '<' has no left operand
 #if  < 3
      ^
CMakeFiles/innoextract.dir/build.make:1105: recipe for target 'CMakeFiles/innoextract.dir/release.cpp.o' failed
```

https://apps.fedoraproject.org/koschei/package/innoextract

**Comment by dscharrer** [comment]
Thanks for the heads up.

Either of the above commits fixes the build with CMake 3.5.0-rc3 if you want to add a patch to the package.

Otherwise, 1.6 is coming soon.

**Comment by a-detiste** [comment]
I don't have enough Fedora experience. I would only update the 1.5 package if that were mandatory,
like the Boost upgrade. Rebuilding with CMake 3.5 doesn't improve the result in any way.

**Comment by dscharrer** [comment]
Fair enough, if the build failing doesn't present any immediate problems then waiting for 1.6 is ok.
